"""Initial Migration

Revision ID: fbc33969f3d7
Revises: 1a60b1306c8c
Create Date: 2019-08-14 10:45:30.900668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc33969f3d7'
down_revision = '1a60b1306c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('conname', sa.String(length=255), nullable=True))
    op.add_column('vote', sa.Column('presidentname', sa.String(length=255), nullable=True))
    op.add_column('vote', sa.Column('womanname', sa.String(length=255), nullable=True))
    op.drop_column('vote', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('vote', 'womanname')
    op.drop_column('vote', 'presidentname')
    op.drop_column('vote', 'conname')
    # ### end Alembic commands ###
